name: Aimylabs Scheduled Posts

on:
  push:
    branches: [ main ]
  schedule:
    # 08:00 and 20:00 PST (UTC-8, no DST adjustment). In UTC: 16:00 and 04:00 next day.
    # Note: GitHub cron is UTC and does NOT auto-adjust for daylight saving time.
    - cron: "0 16 * * *"  # 08:00 PST
    - cron: "0 4 * * *"   # 20:00 PST
  workflow_dispatch: {}

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run one posting cycle
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
          X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
          X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          python -m aimylabs.cli run


