name: Aimylabs Scheduled Posts

on:
  push:
    branches: [ main ]
  schedule:
    # Run at 08:00 and 20:00 America/Los_Angeles year-round.
    # GitHub Actions cron is UTC and does NOT auto-adjust for DST, so we split by months:
    # - PDT (UTC-7): Mar–Oct → 08:00 => 15:00 UTC, 20:00 => 03:00 UTC next day
    # - PST (UTC-8): Nov–Feb → 08:00 => 16:00 UTC, 20:00 => 04:00 UTC next day
    - cron: "0 15 * 3-10 *"  # 08:00 PDT (Mar–Oct)
    - cron: "0 3 * 3-10 *"   # 20:00 PDT (Mar–Oct)
    - cron: "0 16 * 11-12,1,2 *"  # 08:00 PST (Nov–Feb)
    - cron: "0 4 * 11-12,1,2 *"   # 20:00 PST (Nov–Feb)
  workflow_dispatch: {}

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run one posting cycle
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o
          X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
          X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          python -m aimylabs.cli run


